apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: aximo
  labels:
    app.kubernetes.io/name: aximo
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: aximo
